# bbootimg
LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= src/bbootimg.c src/libbootimg.c
LOCAL_MODULE:= bbootimg
LOCAL_MODULE_TAGS := eng

LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_UNSTRIPPED_PATH := $(TARGET_OUT_EXECUTABLES_UNSTRIPPED)

LOCAL_STATIC_LIBRARIES := libc

include $(BUILD_EXECUTABLE)


# bbootimg - dynamic binary for TWRP
include $(CLEAR_VARS)

LOCAL_MODULE:= bbootimg_recovery
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_MODULE_STEM := bbootimg

LOCAL_SRC_FILES:= src/bbootimg.c src/libbootimg.c
LOCAL_SHARED_LIBRARIES := libc

include $(BUILD_EXECUTABLE)


# libbootimg
include $(CLEAR_VARS)
LOCAL_SRC_FILES := src/libbootimg.c
LOCAL_MODULE := libbootimg
LOCAL_MODULE_TAGS := eng
include $(BUILD_STATIC_LIBRARY)
